### ISSUE TITLE
Issues on "Quick tour of Python" Page

### ISSUE THREAD

**Issue by bvegetabile** [python4astronomers/python4astronomers#23]
Concerning information on the following page:
http://python4astronomers.github.io/intro/quick-tour.html

In the first block of code, there is an error in the last line. The code reads...

asciitable.write(dat[with_z], 'fermi_agn_with_z.dat')

which does not work.  Suggest using...

ascii.write(dat[with_z], 'fermi_agn_with_z.dat')

**Comment by hamogu** [comment]
We fixed this a while ago, but forgot to close this issue. Thanks for reporting again!
